markdown: kramdown
destination: build/
#url: http://strangerpixel.com/firstmove-foundation # for live github pages
url: http://localhost:4000 # for local dev
#baseurl: /firstmove-foundation
exclude: [
	'bower_components',
	'node_modules',
	'scss',
	'bower.json',
	'Gemfile',
	'Gemfile.lock',
	'Gruntfile.js',
	'package.json'
]