source: source/
destination: build/
url: http://localhost/firstmove-foundation/build
exclude: [
	'bower_components',
	'node_modules',
	'scss',
	'bower.json',
	'Gemfile',
	'Gemfile.lock',
	'Gruntfile.js',
	'package.json'
]